default_connection_name = ""

[cli]
ignore_new_version_warning = false

[cli.logs]
save_logs = true
path = "C:\\Users\\username\\.snowflake\\logs"
level = "info"

[connections.]
account = ""
user = ""
password = ""
role = ""
